# Generated by Django 4.1.1 on 2022-10-04 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usercomments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenttext', models.CharField(max_length=280)),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='commentA',
        ),
    ]
