# Generated by Django 4.1.1 on 2022-10-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_usercomments_delete_commenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='commentA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenttext', models.CharField(max_length=280)),
                ('username', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ['username'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='usercomments',
        ),
    ]
