# Generated by Django 4.1.1 on 2022-10-04 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_commenta_delete_usercomments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='commentA',
        ),
    ]
