# Generated by Django 4.1.1 on 2022-10-04 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0004_delete_commenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='usercomments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenttext', models.CharField(max_length=280)),
                ('username', models.CharField(max_length=50)),
            ],
        ),
    ]
