# Generated by Django 4.1.1 on 2022-10-04 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_usercomments_thedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('usercomments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.usercomments')),
                ('discription', models.CharField(max_length=280)),
            ],
            bases=('home.usercomments',),
        ),
    ]
