# Generated by Django 4.1.4 on 2022-12-13 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_user_userinformation_u'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address',
        ),
        migrations.AddField(
            model_name='userinformation',
            name='address',
            field=models.CharField(default=1, max_length=280),
            preserve_default=False,
        ),
    ]
