# Generated by Django 4.1.4 on 2022-12-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_address1_userinformation_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='address',
            name='address',
            field=models.CharField(default=0, max_length=280),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default=0, max_length=280),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='zipcode',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
