# Generated by Django 4.1.4 on 2022-12-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_address_address_remove_address_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='productroast',
            field=models.CharField(default=1, max_length=280),
            preserve_default=False,
        ),
    ]
