#adapted from example in docker documentation
version: '3'

services:
  web:
    build: .
    volumes:
       - .:/code
    restart: always
    expose:
         - 8000
    user: 1005:1006
    links:
         - redis:redis
    # ports:
    #  - 8000:8000
    command: python /code/finalassignment2/finalassignment/homepage/manage.py runserver 0.0.0.0:8000
  nginx:
      restart: always
      build: ./nginx/
      depends_on:
          - web
      ports:
          - 80:80
      links:
          - web:web
  redis:
          image: redis:latest
          expose:
                  - 6379
